# FROM node:16
# WORKDIR /app
# COPY package*.json ./
# #COPY tsconfig.*.json ./
# COPY .env ./
# RUN npm install
# COPY ../.. .
# RUN npm run build
# EXPOSE ${PORT}

# CMD [ "npm","run", "start:dev"]
FROM node:lts-alpine as build
WORKDIR /usr/app/src
COPY package*.json .
RUN npm install
COPY . .
EXPOSE ${PORT}
CMD [ "npm","run", "start:dev"]